export const components = [
    { ID: "1", type: 'CPU', Socket: 'AM4', name: 'AMD Ryzen 9 7950X', Descricao: 'O AMD Ryzen 9 7950X é um processador de alto desempenho, ideal para gamers, criadores de conteúdo e entusiastas de tecnologia. Com 16 núcleos e 32 threads, esse processador oferece uma experiência incomparável, com base de 4.5 GHz e boost de até 5.7 GHz. Ele é perfeito para multitarefas intensivas e cargas de trabalho pesadas, garantindo uma performance superior, especialmente em jogos e renderizações. A arquitetura avançada do Ryzen 9 7950X assegura também eficiência energética, com um consumo de 170W, sendo uma escolha excelente para sistemas de alto desempenho.', price: 699.90, watts: 170, img: '../imagens/Componentes/1.png' },
    { ID: "2", type: 'CPU', Socket: 'AM5,AM4', name: 'AMD Ryzen 7 5800X', Descricao: 'O Ryzen 7 5800X é um processador poderoso com 8 núcleos e 16 threads, oferecendo uma excelente performance em jogos e multitarefas. Com um clock base de 3.8 GHz e overclock de até 4.7 GHz, esse modelo é altamente eficaz para tarefas que exigem alto poder de processamento, como edição de vídeo e renderização 3D. A compatibilidade com os sockets AM4 e AM5 torna o Ryzen 7 5800X versátil, garantindo que ele seja adequado para uma ampla gama de placas-mãe. Ele também possui eficiência energética com apenas 105W de consumo.', price: 429.90, watts: 105, img: '../imagens/Componentes/2.png' },
    { ID: "3", type: 'CPU', Socket: 'LGA1700', name: 'Processador Intel Core i9 - 12900K (12ª Geração)', Descricao: 'O Intel Core i9-12900K é um dos processadores mais avançados da Intel, com 16 núcleos e 24 threads, proporcionando uma performance incrível em jogos, criação de conteúdo e tarefas intensivas. Ele possui uma base de 3.2 GHz, com boost de até 5.2 GHz, graças à sua arquitetura híbrida, que combina núcleos de desempenho e eficiência. O i9-12900K é ideal para usuários que exigem o máximo de suas máquinas, oferecendo um desempenho impressionante em todas as frentes, seja para jogos, streaming ou renderização de conteúdo profissional.', price: 339.90, watts: 125, img: '../imagens/Componentes/14.png' },
    { ID: "4", type: 'CPU', Socket: 'AM5,AM4', name: 'AMD Ryzen 5 5600G', Descricao: 'O AMD Ryzen 5 5600G é um processador de 6 núcleos e 12 threads com excelente relação custo-benefício, ideal para quem deseja uma boa performance para jogos e tarefas gerais sem precisar de uma placa gráfica dedicada. Com clock base de 3.9 GHz e boost de até 4.4 GHz, ele oferece grande desempenho em tarefas cotidianas e jogos leves a médios, e é uma excelente opção para quem procura uma solução integrada de GPU. Consome apenas 65W, tornando-o uma opção energética eficiente.', price: 139.90, watts: 65, img: '../imagens/Componentes/15.png' },
    { ID: "5", type: 'CPU', Socket: 'LGA1700', name: 'Processador Intel Core i7 - 13700K (13ª Geração)', Descricao: 'O Intel Core i7-13700K é uma excelente opção para quem busca um processador com desempenho de ponta. Com 16 núcleos e 24 threads, ele oferece desempenho excepcional tanto para jogos quanto para tarefas mais pesadas, como renderizações e edição de vídeos. Com base de 3.4 GHz e boost de até 5.4 GHz, o i7-13700K proporciona um ótimo equilíbrio entre preço e desempenho. Sua eficiência energética é destacada com um consumo de 125W.', price: 369.90, watts: 125, img: '../imagens/Componentes/27.png' },
    
    { ID: "6", type: 'COOLER', name: 'Corsair iCUE H150i Elite LCD XT', Descricao: 'O Corsair iCUE H150i Elite LCD XT é um cooler líquido 360mm projetado para proporcionar refrigeração de alto desempenho para sistemas exigentes. Equipado com um LCD RGB personalizável, ele não só garante um ótimo desempenho térmico, mas também oferece uma estética única para quem deseja personalizar seu PC. Ideal para processadores de alto desempenho, o H150i mantém a temperatura baixa mesmo sob cargas intensas.', price: 279.99, img: '../imagens/Componentes/3.png' },
    { ID: "7", type: 'COOLER', name: 'Cooler CPU Arctic Freezer 34 eSports DUO 120mm Cinza', Descricao: 'O Arctic Freezer 34 eSports DUO é um cooler a ar de alta performance, com design de duplo ventilador para maximizar a dissipação de calor. Ideal para CPUs de médio e alto desempenho, ele oferece uma solução eficaz e silenciosa para manter as temperaturas do processador sob controle. Seu design e tamanho compacto tornam-no perfeito para sistemas mais compactos ou de baixo custo, sem sacrificar a eficiência térmica.', price: 39.90, img: '../imagens/Componentes/4.png' },
    { ID: "8", type: 'COOLER', name: 'Water Cooler CPU NZXT Kraken Elite 360 RGB Preto', Descricao: 'O NZXT Kraken Elite 360 é um sistema de refrigeração líquida 360mm com iluminação RGB personalizável. Este cooler proporciona um desempenho térmico superior, mantendo o processador em temperaturas ideais mesmo em overclock. Ideal para sistemas de alto desempenho e com um design moderno e elegante, ele oferece uma excelente combinação de performance e estética para entusiastas de PC.', price: 309.90, img: '../imagens/Componentes/16.png' },
    { ID: "9", type: 'COOLER', name: 'Corsair iCUE H150i Elite Capellix Liquid Cooler', Descricao: 'O Corsair iCUE H150i Elite Capellix é um cooler líquido de 360mm projetado para oferecer o máximo de desempenho em sistemas de alta performance. Ele possui iluminação RGB Capellix para um visual customizável e mantém os componentes do sistema em temperaturas seguras, mesmo em situações de overclock. Ideal para entusiastas e gamers que buscam uma solução silenciosa e eficiente para o resfriamento do seu processador.', price: 259.90, img: '../imagens/Componentes/25.png' },
   
    { ID: "10", type: 'MOTHERBOARD', Socket: 'AM4', DDR: "DDR4", name: 'Motherboard ATX ASUS ROG STRIX B550-F Gaming', Descricao: 'A motherboard ATX ASUS ROG STRIX B550-F Gaming oferece excelente desempenho para gamers e entusiastas. Com suporte a PCIe 4.0 e Wi-Fi integrado, ela oferece uma experiência de jogo sem interrupções e desempenho em alta velocidade para componentes como SSDs e placas gráficas. Além disso, seus componentes de alta qualidade garantem estabilidade e durabilidade a longo prazo.', price: 199.90, img: '../imagens/Componentes/5.png' },
    { ID: "11", type: 'MOTHERBOARD', Socket: 'AM5', DDR: "DDR5", name: 'Motherboard Mini-ITX Gigabyte B650I Aorus Ultra', Descricao: 'A motherboard Mini-ITX Gigabyte B650I Aorus Ultra é compacta, mas oferece excelente desempenho. Compatível com o socket AM5 e suportando DDR5, ela é perfeita para builds pequenas e poderosas. Seu design robusto e suporte a Wi-Fi integrado fazem dela uma excelente escolha para quem precisa de uma solução compacta sem abrir mão de desempenho.', price: 319.90, img: '../imagens/Componentes/6.png' },
    { ID: "12", type: 'MOTHERBOARD', Socket: 'AM5', DDR:"DDR5", name: 'Motherboard ATX ASRock B650E Steel Legend WiFi', Descricao: 'A ASRock B650E Steel Legend é uma motherboard ATX de alta qualidade, projetada para quem busca desempenho estável e robustez. Com suporte para processadores AMD Ryzen de última geração, ela oferece suporte a memória DDR5, garantindo altas taxas de transferência de dados. A inclusão de Wi-Fi 6 também oferece conectividade sem fio avançada e mais rápida. Seu design agressivo, com dissipadores de calor e recursos de overclock, tornam-na uma excelente opção para entusiastas que desejam uma máquina poderosa. Ideal para aqueles que buscam longevidade e estabilidade em seus projetos de PC.', price: 289.90, img: '../imagens/Componentes/17.png' },
    { ID: "13", type: 'MOTHERBOARD', Socket: 'LGA1700', DDR:"DDR4,DDR5", name: 'Motherboard ATX Gigabyte Z690 Aorus Elite AX WiFi', Descricao: 'A Gigabyte Z690 Aorus Elite AX WiFi é uma motherboard ATX de alto desempenho, projetada para suportar os mais recentes processadores Intel de 12ª geração com socket LGA1700. Esta placa-mãe oferece compatibilidade com memórias DDR4 e DDR5, permitindo que você escolha a melhor opção de memória conforme seu orçamento e necessidade de desempenho. Além disso, ela possui Wi-Fi 6 integrado, proporcionando uma conexão sem fio rápida e estável. Com PCIe 5.0, você estará preparado para futuras atualizações em termos de velocidade e desempenho, tornando-a uma excelente escolha para entusiastas de PCs modernos e gamers exigentes.', price: 209.90, img: '../imagens/Componentes/18.png' },
    { ID: "14", type: 'MOTHERBOARD', Socket: 'AM4', DDR:"DDR4", name: 'Motherboard Micro-ATX Gigabyte B550M DS3H', Descricao: 'A Gigabyte B550M DS3H é uma motherboard Micro-ATX acessível, ideal para quem está montando um PC de alto desempenho sem quebrar o banco. Com suporte para processadores AMD Ryzen com socket AM4, ela oferece um bom equilíbrio entre desempenho e custo-benefício. Sua compatibilidade com DDR4 e PCIe 4.0 permite que você use componentes de última geração, enquanto seus 4 slots de memória oferecem flexibilidade para expansões futuras. Esta placa-mãe é uma ótima opção para quem busca montar um PC de média gama, com estabilidade e recursos suficientes para jogos e tarefas gerais.', price: 119.90, img: '../imagens/Componentes/29.png' },
    { ID: "15", type: 'MOTHERBOARD', Socket: 'LGA1700', DDR:"DDR5", name: 'Motherboard ATX Asus Prime Z790-P WiFi', Descricao: 'A Asus Prime Z790-P é uma motherboard ATX premium, voltada para usuários exigentes que desejam o melhor desempenho em sua máquina. Ela oferece suporte para processadores Intel de 13ª geração com socket LGA1700 e memória DDR5, proporcionando um desempenho excepcional em multitarefas e jogos. A conectividade Wi-Fi 6 garante uma navegação sem fio rápida, enquanto a construção robusta da placa-mãe permite overclock e estabilidade em longas sessões de uso intenso. Ideal para entusiastas que buscam uma plataforma de alto desempenho, com recursos para expansão e customização.', price: 259.90, img: '../imagens/Componentes/36.png' },

    { ID:"16", type: 'CAIXA', name: 'Caixa ATX Corsair iCUE 4000X RGB Tempered Glass Preta', Descricao: 'O Corsair iCUE 4000X RGB é um gabinete ATX premium com vidro temperado, oferecendo não só estética de alta qualidade, mas também excelente fluxo de ar para manter seus componentes refrigerados. Sua iluminação RGB personalizável permite criar uma atmosfera única e atraente no seu PC, e o design interno facilita a organização dos cabos, garantindo uma montagem limpa e eficiente. A caixa é equipada com ventiladores de alto desempenho e tem amplo espaço para placas gráficas de grande porte e sistemas de resfriamento avançados.', price: 109.90, img: '../imagens/Componentes/7.png' },
    { ID:"17", type: 'CAIXA', name: 'Caixa Micro-ATX MSI MAG Pano M100R PZ Series Vidro Temperado', Descricao: 'O MSI MAG Pano M100R PZ Series é um gabinete Micro-ATX de alta qualidade com design compacto e moderno, projetado para quem busca performance em um formato reduzido. Seu vidro temperado de alta transparência exibe seus componentes internos de forma elegante, enquanto o layout interno permite fácil montagem e um excelente fluxo de ar. A caixa também conta com iluminação RGB e é compatível com sistemas de resfriamento a ar e líquidas, tornando-a uma ótima opção para gamers e entusiastas com espaços limitados.', price: 99.90, img: '../imagens/Componentes/8.png' },
    { ID:"18", type: 'CAIXA', name: 'Caixa ATX Lian Li PC-O11 Dynamic', Descricao: 'O Lian Li PC-O11 Dynamic é um gabinete ATX premium, conhecido por seu design elegante e excelente fluxo de ar. Com vidro temperado nas laterais e frontal, ele oferece uma visão panorâmica do interior da sua máquina, permitindo destacar seus componentes, principalmente se você estiver usando iluminação RGB. O PC-O11 Dynamic oferece amplo espaço interno para placas gráficas grandes e sistemas de resfriamento avançados, sendo uma excelente escolha para montagens de alto desempenho e de aparência atraente.', price: 169.90, img: '../imagens/Componentes/19.png' },
    { ID:"19", type: 'CAIXA', name: 'Caixa ATX Corsair iCUE 5000T RGB Tempered Glass Preta', Descricao: 'A Corsair iCUE 5000T RGB é um gabinete ATX projetado para oferecer o melhor em termos de ventilação e personalização de iluminação. Ele suporta até 10 ventoinhas, garantindo excelente fluxo de ar para seus componentes. O design elegante com vidro temperado e iluminação RGB avançada oferece uma experiência visual imersiva, enquanto seu layout interno permite montagem de sistemas poderosos com facilidade, com suporte para placas gráficas de grandes dimensões e resfriamento a ar ou líquido.', price: 329.90, img: '../imagens/Componentes/30.png' },
    { ID:"20", type: 'CAIXA', name: 'Caixa ATX Fractal Design Meshify 2 Compact Lite Black', Descricao: 'O Fractal Design Meshify 2 Compact Lite é um gabinete ATX compacto, projetado para oferecer alto desempenho em um formato menor. Sua excelente ventilação é garantida por um painel frontal em malha, que permite que o ar flua livremente para os componentes. O design clean e minimalista do gabinete o torna ideal para quem prefere um visual discreto e eficiente, enquanto o layout interno otimiza a organização e a montagem dos componentes.', price: 109.90, img: '../imagens/Componentes/37.png' },

    { ID:"21", type: 'FONTE', watts: 750, name: 'Fonte Corsair RM750x 750W 80 Plus Gold Full Modular', Descricao: 'A Corsair RM750x é uma fonte de alimentação modular de 750W, certificada com a classificação 80 Plus Gold, oferecendo excelente eficiência energética e baixo nível de ruído. A fonte possui cabos totalmente modulares, permitindo um gerenciamento de cabos mais limpo e organizado, ideal para builds que exigem um fluxo de ar otimizado. Sua confiabilidade e durabilidade a tornam uma excelente escolha para gamers e entusiastas que buscam alto desempenho e estabilidade em suas máquinas.', price: 99.90, img: '../imagens/Componentes/9.png' },
    { ID:"22", type: 'FONTE', watts: 650, name: 'Fonte de Alimentação ATX MSI MAG A650BN 650W 80 Plus Bronze', Descricao: 'A MSI MAG A650BN é uma fonte de alimentação com 650W de potência e certificação 80 Plus Bronze, garantindo boa eficiência e desempenho em builds de médio porte. Ela oferece construção robusta e estabilidade para sistemas de gaming ou produtividade, com proteção contra sobrecarga e curto-circuito. Seu design compacto permite que ela se encaixe facilmente em gabinetes menores, sendo ideal para quem busca uma solução acessível e confiável para sua máquina.', price: 59.90, img: '../imagens/Componentes/10.png' },
    { ID:"23", type: 'FONTE', watts: 650, name: 'Fonte de Alimentação ATX EVGA GQ 650W 80 Plus Gold Semi Modular', Descricao: 'A EVGA GQ 650W é uma fonte de alimentação semi-modular com certificação 80 Plus Gold, oferecendo excelente eficiência energética e excelente desempenho para sistemas de gaming e produtividade. A semi-modularidade permite uma instalação mais prática e um gerenciamento de cabos mais limpo, enquanto sua proteção de segurança garante uma operação estável e segura para o seu PC.', price: 96.90, img: '../imagens/Componentes/20.png' },
    { ID:"24", type: 'FONTE', watts: 750, name: 'Fonte de Alimentação SFX Corsair SF Series (2024) SF750 750W 80 PLUS Platinum Full Modular', Descricao: 'A Corsair SF750 é uma fonte de alimentação SFX compacta e poderosa, com certificação 80 Plus Platinum, oferecendo eficiência superior e desempenho para sistemas compactos e de alto desempenho. Sua modularidade total permite um gerenciamento de cabos mais eficiente, e ela é ideal para PCs pequenos ou de formato ITX, onde o espaço é limitado, mas o desempenho não pode ser comprometido.', price: 183.90, img: '../imagens/Componentes/21.png' },
    { ID:"25", type: 'FONTE', watts: 1000, name: 'Fonte de Alimentação ATX Corsair HX1000i 1000W 80 Plus Platinum Full Modular', Descricao: 'A Corsair HX1000i é uma fonte de alimentação de 1000W com certificação 80 Plus Platinum, oferecendo altíssima eficiência e estabilidade para sistemas de alta performance. Ideal para PCs de alto desempenho, como os usados para gaming avançado, edição de vídeo e tarefas intensivas de computação, esta fonte garante um fornecimento de energia estável, com cabos modulares para um gerenciamento de cabos mais limpo e fácil.', price: 268.90, img: '../imagens/Componentes/31.png' },
    { ID:"26", type: 'FONTE', watts: 1200, name: 'Fonte de Alimentação ATX NZXT C1200 (2023) 1200W 80 Plus Gold Full', Descricao: 'A NZXT C1200 é uma fonte de alimentação robusta de 1200W, com certificação 80 Plus Gold, ideal para sistemas de PC que exigem uma grande quantidade de energia, como configurações multi-GPU ou builds para servidores. Sua alta capacidade de fornecimento de energia e a eficiência 80 Plus Gold garantem um funcionamento estável e econômico para as configurações mais exigentes.', price: 179.90, img: '../imagens/Componentes/39.png' },
    
    { ID: "27", type: 'ARMAZENAMENTO', name: 'SSD M.2 2280 Kingston KC3000 2TB 3D TLC NVMe PCIe Gen 4.0', Descricao: 'O Kingston KC3000 é um SSD de alto desempenho projetado para entusiastas e profissionais que buscam o máximo de velocidade e capacidade. Com uma interface PCIe Gen 4.0 e uma capacidade de 2TB, oferece velocidades de leitura e gravação extremamente rápidas, ideais para tarefas exigentes como jogos, edição de vídeo em alta resolução e manipulação de grandes arquivos. Equipado com a tecnologia 3D TLC, o KC3000 combina durabilidade com performance superior, proporcionando tempos de carregamento mais rápidos e um sistema mais ágil. Este SSD é uma excelente escolha para quem quer o melhor em armazenamento para PC.', price: 162.90, img: '../imagens/Componentes/11.png' }, 
    { ID: "28", type: 'ARMAZENAMENTO', name: 'SSD M.2 2280 Kingston NV2 500GB 3D QLC NVMe', Descricao: 'O Kingston NV2 é um SSD NVMe de baixo custo com alto desempenho, projetado para atender a usuários que desejam melhorar a velocidade e eficiência do sistema sem comprometer o orçamento. Com 500GB de capacidade e a tecnologia 3D QLC, oferece boa velocidade de leitura e gravação para usuários casuais e gamers. Sua interface NVMe permite um desempenho significativamente superior ao dos SSDs SATA, o que resulta em carregamentos mais rápidos, maior capacidade de resposta e melhor performance geral do sistema. Ideal para quem procura um bom custo-benefício sem abrir mão de qualidade.', price: 44.90, img: '../imagens/Componentes/32.png' },
    { ID: "29", type: 'ARMAZENAMENTO', name: 'SSD M.2 2280 Samsung 980 Pro 2TB', Descricao: 'O Samsung 980 Pro é um SSD NVMe de alto desempenho, projetado para os usuários mais exigentes que buscam velocidade e capacidade excepcionais. Com uma interface PCIe Gen 4.0, este SSD oferece velocidades de leitura e gravação impressionantes, tornando-o ideal para tarefas intensivas, como edição de vídeo em 4K, jogos de última geração e aplicativos de design. Com 2TB de capacidade, oferece amplo espaço para armazenar grandes arquivos e jogos, enquanto a sua tecnologia avançada assegura durabilidade e confiabilidade. Se você deseja um upgrade rápido e confiável, o 980 Pro é a escolha perfeita para aumentar o desempenho do seu sistema.', price: 169.90, img: '../imagens/Componentes/22.png' }, 
    
    { ID: "30", type: 'RAM', DDR: "DDR4", name: 'Memória RAM Corsair Vengeance LPX 16GB (2x8GB) DDR4-3200MHz', Descricao: 'A memória Corsair Vengeance LPX oferece desempenho de alta qualidade com 16GB (2x8GB) de capacidade DDR4 e frequência de 3200MHz. Ideal para gamers e entusiastas de PC que buscam estabilidade e velocidade em seus sistemas. O design de perfil baixo facilita a instalação em sistemas compactos, enquanto a alta velocidade proporciona excelente desempenho em jogos e multitarefas. A Corsair Vengeance LPX é perfeita para quem quer otimizar a performance de sua máquina sem comprometer o orçamento.', price: 49.90, img: '../imagens/Componentes/12.png' }, 
    { ID: "31", type: 'RAM', DDR: "DDR5", name: 'Memória RAM G.SKILL Trident Z5 RGB 32GB (2x16GB) DDR5-6400MHz CL32 Preta', Descricao: 'A memória G.SKILL Trident Z5 RGB é uma das melhores opções para quem busca desempenho extremo. Com 32GB (2x16GB) de capacidade e uma impressionante frequência de 6400MHz, ela oferece uma performance sem igual em tarefas pesadas como jogos, edição de vídeos em 4K e renderização 3D. O design sofisticado com iluminação RGB adiciona um toque visual impressionante ao seu PC, enquanto a tecnologia DDR5 garante eficiência energética superior e velocidade. Ideal para quem deseja construir uma máquina de alto desempenho com estilo.', price: 153.90, img: '../imagens/Componentes/13.png' }, 
    { ID: "32", type: 'RAM', DDR: "DDR4", name: 'Memória RAM Corsair Dominator Platinum RGB 16GB (2x8GB) DDR4-3600MHz', Descricao: 'A Corsair Dominator Platinum RGB combina desempenho de elite com um visual impressionante. Com 16GB (2x8GB) de memória DDR4 e frequência de 3600MHz, esta memória oferece estabilidade e rapidez em qualquer sistema. O design premium com iluminação RGB personalizável faz da Dominator uma das opções mais cobiçadas entre os entusiastas. Ideal para aqueles que buscam o melhor em desempenho e estilo, essa memória garante um upgrade significativo para qualquer PC de alta performance.', price: 89.90, img: '../imagens/Componentes/35.png' }, 
    
    { ID: "33", type: 'GPU', name: 'Placa Gráfica Sapphire AMD Radeon RX 7900 XT', Descricao: 'A Sapphire AMD Radeon RX 7900 XT é uma placa gráfica de alto desempenho projetada para gamers e criadores de conteúdo. Com 24GB de memória GDDR6 e suporte a Ray Tracing, ela oferece gráficos incrivelmente detalhados e experiências de jogo imersivas. Sua arquitetura RDNA 3 da AMD garante eficiência e desempenho excepcionais, tornando-a ideal para rodar jogos em 4K e outras tarefas gráficas intensivas com altas taxas de quadros. Se você busca um desempenho gráfico de ponta, a RX 7900 XT é uma excelente escolha.', price: 569.90, watts: 355, img: '../imagens/Componentes/23.png' }, 
    { ID: "34", type: 'GPU', name: 'Placa Gráfica Asus NVIDIA GeForce RTX 4070 SUPER', Descricao: 'A placa gráfica Asus NVIDIA GeForce RTX 4070 SUPER oferece um desempenho incrível para gamers e criadores de conteúdo. Com 12GB de memória GDDR6X e suporte a DLSS 3.0, ela garante gráficos realistas e taxas de quadros suaves, mesmo nos jogos mais exigentes. O Ray Tracing em tempo real proporciona efeitos visuais impressionantes, enquanto a arquitetura Ada Lovelace da NVIDIA garante uma performance excepcional e eficiência energética. Ideal para quem deseja jogar em 1440p ou 4K com qualidade gráfica de ponta.', price: 639.90, watts: 220, img: '../imagens/Componentes/24.png' }, { ID: "35", type: 'GPU', name: 'Placa Gráfica Asus NVIDIA GeForce RTX 4060 "Ada Lovelace" Dual White Edition', Descricao: 'A ASUS NVIDIA GeForce RTX 4060 "Ada Lovelace" Dual White Edition é uma placa gráfica de alto desempenho com 8GB de memória GDDR6 e um design elegante. Ela oferece um ótimo equilíbrio entre preço e desempenho, tornando-a ideal para jogos em 1080p e 1440p, além de suporte a DLSS 3.0 e Ray Tracing para uma experiência visual de alta qualidade. Seu design compacto e elegante, combinado com a tecnologia de ponta da NVIDIA, oferece uma excelente opção para quem busca um bom desempenho gráfico sem comprometer o orçamento.', price: 359.90, watts: 115, img: '../imagens/Componentes/33.png' }, { ID: "36", type: 'GPU', name: 'Placa Gráfica Powercolor AMD Radeon RX 7700 XT', Descricao: 'A Powercolor AMD Radeon RX 7700 XT é uma placa gráfica de 12GB GDDR6 que oferece um excelente custo-benefício para gamers. Ela é perfeita para quem busca uma boa performance em 1440p ou 1080p, com suporte a Ray Tracing e gráficos de alta qualidade. A RX 7700 XT é equipada com a arquitetura RDNA 3 da AMD, que proporciona maior eficiência energética e desempenho em jogos. Se você está montando um PC para jogos sem gastar uma fortuna, esta placa gráfica oferece um ótimo equilíbrio entre preço e desempenho.', price: 499.90, watts: 245, img: '../imagens/Componentes/34.png' }, 
    { ID: "37", type: 'GPU', name: 'Placa Gráfica MSI NVIDIA GeForce RTX 4080 SUPER', Descricao: 'A MSI NVIDIA GeForce RTX 4080 SUPER é a escolha definitiva para gamers e profissionais que buscam o máximo desempenho. Com 16GB de memória GDDR6X e suporte a Ray Tracing, ela oferece um desempenho de tirar o fôlego em 4K e outras tarefas gráficas exigentes. Equipado com a arquitetura Ada Lovelace da NVIDIA, a RTX 4080 SUPER garante gráficos incrivelmente detalhados e altas taxas de quadros em jogos AAA e tarefas criativas. Para quem deseja uma experiência gráfica superior, essa placa é a melhor escolha para construir um PC de alto desempenho.', price: 1169.90, watts: 320, img: '../imagens/Componentes/38.png' }






    
    //{ type: 'GPU', name: 'Placa Gráfica ASUS ROG STRIX AMD Radeon RX 6800 XT', price: 599.90, img: '../imagens/Componentes/120000.png' },
    //{ type: 'GPU', name: 'Placa Gráfica Zotac NVIDIA GeForce GTX 1660 Super', price: 239.90, img: '../imagens/Componentes/1300000.png' },
    //{ type: 'COOLER', name: 'Deepcool AS500 Plus ARGB Air Cooler', price: 59.90, img: '../imagens/Componentes/1300000.png' },
    //{ type: 'CAIXA', name: 'Caixa ATX Cooler Master MasterBox TD500 Mesh ARGB', price: 109.90, img: '../imagens/Componentes/1300000.png' },
    //{ type: 'ARMAZENAMENTO', name: 'HDD 3.5" Western Digital Black 4TB', price: 129.90, img: '../imagens/Componentes/1300000.png' },
    //{ type: 'RAM', name: 'Memória RAM Crucial Ballistix 16GB (2x8GB) DDR4-3600MHz', price: 64.90, img: '../imagens/Componentes/1300000.png' },
    //{ type: 'RAM', name: 'Memória RAM ADATA XPG Spectrix D50 RGB 32GB (2x16GB) DDR4-3600MHz', price: 139.90, img: '../imagens/Componentes/1300000.png' },
    //{ type: 'CAIXA', name: 'Caixa ITX NZXT H1 v2 Compact Case', price: 349.90, img: '../imagens/Componentes/1300000.png' },
    //{ type: 'ARMAZENAMENTO', name: 'SSD M.2 Samsung 870 QVO 2TB SATA', price: 99.90, img: '../imagens/Componentes/1300000.png' },
    //{ type: 'COOLER', name: 'Thermaltake Floe DX RGB 280 TT Premium Edition', price: 149.90, img: '../imagens/Componentes/52.png' },
    //{ type: 'CAIXA', name: 'Caixa ATX Phanteks Eclipse P400A Digital', price: 99.90, img: '../imagens/Componentes/56.png' },
    //{ type: 'FONTE', name: 'Fonte Cooler Master V750 SFX Gold Full Modular', price: 159.90, img: '../imagens/Componentes/57.png' },
    //{ type: 'ARMAZENAMENTO', name: 'HDD Toshiba X300 Performance 6TB', price: 159.90, img: '../imagens/Componentes/60.png' },
    //{ type: 'RAM', name: 'Memória RAM TeamGroup T-Force Delta RGB 32GB (2x16GB) DDR5-5600MHz', price: 179.90, img: '../imagens/Componentes/64.png' },
    //{ type: 'ARMAZENAMENTO', name: 'SSD Corsair MP600 PRO LPX 1TB PCIe Gen4', price: 89.90, img: '../imagens/Componentes/68.png' },
    //{ type: 'RAM', name: 'Memória RAM PNY XLR8 Gaming EPIC-X RGB 32GB (2x16GB) DDR5-6200MHz', price: 199.90, img: '../imagens/Componentes/71.png' },
];
